export interface Skill {
  name: string;
  point: number;
  base: number;
  correction?: 'HALF_DEX';
}

// 크툴루의 부름 탐사자 기능들의 초기 목록
export const INITIAL_SKILLS: Skill[] = [
  {name: "예술/공예()" , point: 0, base: 5},
  {name: "회계" , point: 0, base: 5},
  {name: "인류학" , point: 0, base: 1},
  {name: "감정" , point: 0, base: 5},
  {name: "고고학" , point: 0, base: 1},
  {name: "매혹" , point: 0, base: 15},
  {name: "오르기" , point: 0, base: 20},
  {name: "컴퓨터 사용" , point: 0, base: 5},
  {name: "재력" , point: 0, base: 0},
  {name: "변장" , point: 0, base: 5},
  {name: "회피" , point: 0, base: 0, correction: 'HALF_DEX'},
  {name: "자동차 운전" , point: 0, base: 20},
  {name: "전기 수리" , point: 0, base: 10},
  {name: "전자기기" , point: 0, base: 1},
  {name: "말재주" , point: 0, base: 5},
  {name: "근접전 (격투)" , point: 0, base: 25},
  {name: "사격 (권총)" , point: 0, base: 20},
  {name: "사격(라이플/산탄총)" , point: 0, base: 25},
  {name: "응급처치" , point: 0, base: 30},
  {name: "역사" , point: 0, base: 5},
  {name: "위협" , point: 0, base: 15},
  {name: "도약" , point: 0, base: 20},
  {name: "언어(모국어)" , point: 0, base: 0},
  {name: "언어()" , point: 0, base: 1},
  {name: "법률" , point: 0, base: 5},
  {name: "자료조사" , point: 0, base: 20},
  {name: "듣기" , point: 0, base: 20},
  {name: "열쇠공" , point: 0, base: 1},
  {name: "기계 수리" , point: 0, base: 10},
  {name: "의학" , point: 0, base: 1},
  {name: "자연" , point: 0, base: 10},
  {name: "항법" , point: 0, base: 10},
  {name: "오컬트" , point: 0, base: 5},
  {name: "설득" , point: 0, base: 10},
  {name: "조종()" , point: 0, base: 1},
  {name: "정신분석" , point: 0, base: 1},
  {name: "심리학" , point: 0, base: 10},
  {name: "승마" , point: 0, base: 5},
  {name: "과학()" , point: 0, base: 1},
  {name: "손놀림" , point: 0, base: 10},
  {name: "관찰력" , point: 0, base: 25},
  {name: "은밀행동" , point: 0, base: 10},
  {name: "생존술()" , point: 0, base: 10},
  {name: "수영" , point: 0, base: 20},
  {name: "투척" , point: 0, base: 20},
  {name: "추적" , point: 0, base: 10},
  {name: "[추가기능 1]" , point: 0, base: 0},
  {name: "[추가기능 2]" , point: 0, base: 0},
  {name: "[추가기능 3]" , point: 0, base: 0},
];
