export interface Skill {
  name: string;
  point: number;
  base: number;
  evade?: 'HALF_DEX';
  motherTongue?: 'EDUCATION';
}

// 크툴루의 부름 탐사자 기능들의 초기 목록
export const INITIAL_SKILLS: Skill[] = [
  { name: "감정", point: 0, base: 5 },
  { name: "고고학", point: 0, base: 1 },
  { name: "과학()", point: 0, base: 1 },
  { name: "관찰력", point: 0, base: 25 },
  { name: "근접전 (격투)", point: 0, base: 25 },
  { name: "기계수리", point: 0, base: 10 },
  { name: "도약", point: 0, base: 20 },
  { name: "듣기", point: 0, base: 20 },
  { name: "말재주", point: 0, base: 5 },
  { name: "매혹", point: 0, base: 15 },
  { name: "법률", point: 0, base: 5 },
  { name: "변장", point: 0, base: 5 },
  { name: "사격 (권총)", point: 0, base: 20 },
  { name: "사격(라/산)", point: 0, base: 25 },
  { name: "생존술()", point: 0, base: 10 },
  { name: "설득", point: 0, base: 10 },
  { name: "손놀림", point: 0, base: 10 },
  { name: "수영", point: 0, base: 20 },
  { name: "승마", point: 0, base: 5 },
  { name: "심리학", point: 0, base: 10 },
  { name: "언어()", point: 0, base: 1 },
  { name: "언어(모국어)", point: 0, base: 0, motherTongue: 'EDUCATION' },
  { name: "역사", point: 0, base: 5 },
  { name: "열쇠공", point: 0, base: 1 },
  { name: "예술/공예()", point: 0, base: 5 },
  { name: "오르기", point: 0, base: 20 },
  { name: "오컬트", point: 0, base: 5 },
  { name: "위협", point: 0, base: 15 },
  { name: "은밀행동", point: 0, base: 10 },
  { name: "응급처치", point: 0, base: 30 },
  { name: "의학", point: 0, base: 1 },
  { name: "인류학", point: 0, base: 1 },
  { name: "자동차 운전", point: 0, base: 20 },
  { name: "자료조사", point: 0, base: 20 },
  { name: "자연", point: 0, base: 10 },
  { name: "재력", point: 0, base: 0 },
  { name: "전기 수리", point: 0, base: 10 },
  { name: "전자기기", point: 0, base: 1 },
  { name: "정신분석", point: 0, base: 1 },
  { name: "조종()", point: 0, base: 1 },
  { name: "추적", point: 0, base: 10 },
  { name: "컴퓨터 사용", point: 0, base: 5 },
  { name: "투척", point: 0, base: 20 },
  { name: "항법", point: 0, base: 10 },
  { name: "회계", point: 0, base: 5 },
  { name: "회피", point: 0, base: 0, evade: 'HALF_DEX' },
  { name: "[추가기능 1]", point: 0, base: 1 },
  { name: "[추가기능 2]", point: 0, base: 1 },
  { name: "[추가기능 3]", point: 0, base: 1 },
  { name: "[추가기능 4]", point: 0, base: 1 },
];
